src/Entity/SerialLetter.php
<?php

/*
 * Copyright (C) 2022 by Luc Hamers <vereniging@hamers.de>
 *
 * This file is part of Vereniging.
 *
 * Vereniging is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Vereniging is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Vereniging.  If not, see <https://www.gnu.org/licenses/>.
 */

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * App\Entity\SerialLetter
 *
 * @ORM\Entity(repositoryClass="App\Repository\SerialLetterRepository")
 * @ORM\Table(name="serial_letter", indexes={@ORM\Index(name="fk_serial_letter_member_entry1",
 * columns={"first_signature_member_id"}), @ORM\Index(name="fk_serial_letter_member_entry2",
 * columns={"second_signature_member_id"})})
 */
class SerialLetter implements EntityLoggerInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="smallint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="date")
     *
     * @Gedmo\Timestampable(on="create")
     */
    protected $createDate;

    /**
     * @ORM\Column(type="date")
     *
     * @Gedmo\Timestampable(on="update")
     */
    protected $changeDate;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $signatureUseTitle;

    /**
     * @ORM\OneToMany(targetEntity="SerialLetterContent", mappedBy="serialLetter", cascade={"remove"})
     * @ORM\JoinColumn(name="id", referencedColumnName="serial_letter_id")
     */
    protected $serialLetterContents;

    /**
     * @ORM\ManyToOne(targetEntity="MemberEntry")
     * @ORM\JoinColumn(name="first_signature_member_id", referencedColumnName="id", nullable=true)
     */
    protected $firstSignatureMember;

    /**
     * @ORM\ManyToOne(targetEntity="MemberEntry")
     * @ORM\JoinColumn(name="second_signature_member_id", referencedColumnName="id", nullable=true)
     */
    protected $secondSignatureMember;

    /**
     * @ORM\ManyToOne(targetEntity="CommitteeFunctionMap")
     * @ORM\JoinColumn(name="fist_signature_function_id", referencedColumnName="id", nullable=true, onDelete="SET NULL")
     */
    protected $firstSignatureMembersFunction;

    /**
     * @ORM\ManyToOne(targetEntity="CommitteeFunctionMap")
     * @ORM\JoinColumn(name="second_signature_function", referencedColumnName="id", nullable=true, onDelete="SET NULL")
     */
    protected $secondSignatureFunction;

    /**
     * @ORM\ManyToOne(targetEntity="MemberEntry")
     * @ORM\JoinColumn(name="last_updated_by_id", referencedColumnName="id", nullable=false)
     */
    protected $lastUpdatedBy;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->serialLetterContents = new ArrayCollection();
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the value of create_date.
     *
     * @return \DateTime
     */
    public function getCreateDate()
    {
        return $this->createDate;
    }

    /**
     * Get the value of change_date.
     *
     * @return \DateTime
     */
    public function getChangeDate()
    {
        return $this->changeDate;
    }

    /**
     * Set the value of signature_use_title.
     *
     * @param boolean $signatureUseTitle
     */
    public function setSignatureUseTitle($signatureUseTitle)
    {
        $this->signatureUseTitle = $signatureUseTitle;
    }

    /**
     * Get the value of signature_use_title.
     *
     * @return boolean
     */
    public function getSignatureUseTitle()
    {
        return $this->signatureUseTitle;
    }

    /**
     * Add SerialLetterContent entity to collection (one to many).
     *
     * @param SerialLetterContent $serialLetterContent
     */
    public function addSerialLetterContent(SerialLetterContent $serialLetterContent)
    {
        $this->serialLetterContents[] = $serialLetterContent;
        $serialLetterContent->setSerialLetter($this);
    }

    /**
     * Get SerialLetterContent entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection|SerialLetterContent[]
     */
    public function getSerialLetterContents()
    {
        return $this->serialLetterContents;
    }

    /**
     * Set MemberEntry entity related by `first_signature_member_id` (many to one).
     *
     * @param MemberEntry $memberEntry
     */
    public function setFirstSignatureMember(MemberEntry $memberEntry = null)
    {
        $this->firstSignatureMember = $memberEntry;
    }

    /**
     * Get MemberEntry entity related by `first_signature_member_id` (many to one).
     *
     * @return MemberEntry
     */
    public function getFirstSignatureMember()
    {
        return $this->firstSignatureMember;
    }

    /**
     * Set MemberEntry entity related by `second_signature_member_id` (many to one).
     *
     * @param MemberEntry $memberEntry
     */
    public function setSecondSignatureMember(MemberEntry $memberEntry = null)
    {
        $this->secondSignatureMember = $memberEntry;
    }

    /**
     * Get MemberEntry entity related by `second_signature_member_id` (many to one).
     *
     * @return MemberEntry
     */
    public function getSecondSignatureMember()
    {
        return $this->secondSignatureMember;
    }

    /**
     * @return CommitteeFunctionMap|null
     */
    public function getFirstSignatureMembersFunction()
    {
        return $this->firstSignatureMembersFunction;
    }

    /**
     * @param CommitteeFunctionMap|null $function
     */
    public function setFirstSignatureMembersFunction($function = null)
    {
        $this->firstSignatureMembersFunction = $function;
    }

    /**
     * @return CommitteeFunctionMap|null
     */
    public function getSecondSignatureMembersFunction()
    {
        return $this->secondSignatureFunction;
    }

    /**
     * @param CommitteeFunctionMap|null $function
     */
    public function setSecondSignatureMembersFunction($function = null)
    {
        $this->secondSignatureFunction = $function;
    }

    /**
     * @return MemberEntry
     */
    public function getLastUpdatedBy()
    {
        return $this->lastUpdatedBy;
    }

    /**
     * @param MemberEntry $lastUpdatedBy
     */
    public function setLastUpdatedBy(MemberEntry $lastUpdatedBy)
    {
        $this->lastUpdatedBy = $lastUpdatedBy;
    }

    /**
     * @param \DateTime $changeDate
     */
    public function setChangeDate(\DateTime $changeDate)
    {
        $this->changeDate = $changeDate;
    }


    /**
     * Get the title for this serial letter for the selected language. If the language is not found, return the title of
     * the first language found. If no content is found, return '',
     *
     * @param Language|string $language
     *
     * @return string Title in selected language, '' if not found.
     */
    public function getTitle($language)
    {
        $content = $this->getContent($language);
        if (is_null($content)) {
            return '';
        }

        return $content->getLetterTitle();
    }

    /**
     * Return the titles for this letter for each language as a string.
     *
     * @return string
     */
    public function getTitles()
    {
        $titles = '';

        /** @var SerialLetterContent $content */
        foreach ($this->serialLetterContents as $content) {
            $titles .= $content->getLanguage()->getLocale().': '.$content->getLetterTitle().'; ';
        }

        // Remove last semicolon
        if ('' !== $titles) {
            $titles = substr($titles, 0, -2);
        }

        return $titles;
    }

    /**
     * Get the content for this serial letter for the selected language. If the language is not found, return the
     * content of the first language found. If no content is found, return '',
     *
     * @param Language|string $language
     *
     * @return SerialLetterContent|null Content in selected language, null if not found.
     */
    public function getContent($language)
    {
        // $language can be either a string or a language object. If it is a language object, read the locale as string.
        if ((is_object($language)) && ('Language' === substr(get_class($language), -strlen('Language')))) {
            $language = $language->getLocale();
        }

        /** @var SerialLetterContent $content */
        foreach ($this->serialLetterContents as $content) {
            if ($content->getLanguage()->getLocale() === $language) {
                return $content;
            }
        }

        if (count($this->serialLetterContents)) {
            return $this->serialLetterContents[0];
        }

        return null;
    }

    /**
     * This method must return an associative array with the following fields:
     * className:   name of the class for which the content is saved
     * index:       index of the current entity
     * content:     array in which the fields of the entity and their values are stored.
     * change_type: string containing the change type to be logged.
     *
     * @return LogEntityChangeContainer
     *
     * @throws \Exception
     */
    public function getEntityContent()
    {
        $contentContainer = new LogEntityChangeContainer();
        $contentContainer->setClassName(get_class($this));
        $contentContainer->setIndex($this->id);
        $shortContent = [];
        /** @var SerialLetterContent $content */
        foreach ($this->serialLetterContents as $content) {

src/Controller/Dashboard/ClubStructureController.php
<?php

/*
 * Copyright (C) 2022 by Luc Hamers <vereniging@hamers.de>
 *
 * This file is part of Vereniging.
 *
 * Vereniging is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Vereniging is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Vereniging.  If not, see <https://www.gnu.org/licenses/>.
 */

namespace App\Controller\Dashboard;

use App\Entity\Committee;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Controller for showing the club structure.
 *
 * @Security("is_granted('ROLE_VIEW_CLUB_STRUCTURE')")
 */
class ClubStructureController extends AbstractController
{
    private bool $useAcademicTitles;


    /**
     * ClubStructureController constructor.
     *
     * @param string $useAcademicTitles
     */
    public function __construct(string $useAcademicTitles)
    {
        $this->useAcademicTitles = ($useAcademicTitles === 'true');
    }


    /**
     * Display the club structure.
     *
     * @Route("/dashboard/clubstructure", name="dashboard_club_structure")
     *
     * @param EntityManagerInterface $entityManager
     *
     * @return Response
     */
    public function indexAction(EntityManagerInterface $entityManager): Response
    {
        $committees = $entityManager->getRepository(Committee::class)
                                    ->getAllCommitteeInformation($this->useAcademicTitles);

        return $this->render('Dashboard/club_structure.html.twig', ['committees' => $committees]);
    }
}

src/Controller/Dashboard/DefaultController.php
<?php

/*
 * Copyright (C) 2022 by Luc Hamers <vereniging@hamers.de>
 *
 * This file is part of Vereniging.
 *
 * Vereniging is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Vereniging is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Vereniging.  If not, see <https://www.gnu.org/licenses/>.
 */

namespace App\Controller\Dashboard;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Controller for the dashboard.
 *
 */
class DefaultController extends AbstractController
{
    /**
     * Show dashboard page.
     *
     * @Route("/dashboard", name="dashboard_homepage")
     *
     * @return Response
     */
    public function indexAction(): Response
    {
        return $this->render('Dashboard/index.html.twig');
    }

    /**
     * Show about this software page.
     *
     * @Route("/dashboard/about", name="dashboard_about")
     *
     * @return Response
     */
    public function aboutAction(): Response
    {
        return $this->render('Dashboard/about.html.twig');
    }
}

src/Controller/Dashboard/LogfileController.php
<?php

/*
 * Copyright (C) 2022 by Luc Hamers <vereniging@hamers.de>
 *
 * This file is part of Vereniging.
 *
 * Vereniging is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Vereniging is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Vereniging.  If not, see <https://www.gnu.org/licenses/>.
 */

namespace App\Controller\Dashboard;

use App\Entity\LogfileEntry;
use App\Form\LogfileEntrySelectionType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * Class LogfileController
 *
 * @Security("is_granted('ROLE_VIEW_LOG_FILE')")
 */
class LogfileController extends AbstractController
{
    /**
     * Show the mailing lists.
     *
     * @Route("/dashboard/logfile", name="dashboard_logfile")
     *
     * @param EntityManagerInterface $entityManager
     * @param TranslatorInterface    $translator
     *
     * @return Response
     */
    public function indexAction(EntityManagerInterface $entityManager, TranslatorInterface $translator): Response
    {

        $numberLimit = 10;
        $logfileEntries = $entityManager->getRepository(LogfileEntry::class)
                                        ->findBy([], ['date' => 'DESC', 'id' => 'DESC'], $numberLimit);
        $form = $this->createForm(LogfileEntrySelectionType::class, null, ['selectedNumber' => $numberLimit]);

        LogfileEntry::prepareTranslation($entityManager, $translator, $this->getUser()->getPreferredLanguage()->getLocale());

        return $this->render('Dashboard/logfile.html.twig', [
            'logfileEntries' => $logfileEntries,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Show main member lists page.
     *
     * @Route("/dashboard/logfile/show", name="core_dashboard_logfile_show")
     *
     * @param Request                $request
     * @param EntityManagerInterface $entityManager
     * @param TranslatorInterface    $translator
     *
     * @return Response
     *
     * @throws \Exception
     */
    public function showAction(Request $request, EntityManagerInterface $entityManager, TranslatorInterface $translator): Response
    {
        $form = $this->createForm(LogfileEntrySelectionType::class);

        $logfileEntries = [];
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $numberLimit = $form->getData()['numberLimit'];
            $logfileEntries = $entityManager->getRepository(LogfileEntry::class)
                                            ->findAllByParameters(
                                                $numberLimit,
                                                $form->getData()['changeType'],
                                                $form->getData()['dateRange'],
                                                $form->getData()['searchWhat'],
                                                $form->getData()['searchByWhom'],
                                                $form->getData()['searchOnWho']
                                            );

            LogfileEntry::prepareTranslation($entityManager, $translator, $this->getUser()->getPreferredLanguage()->getLocale());
        }

        return $this->render('Dashboard/logfile_entry_table.html.twig', [
            'logfileEntries' => $logfileEntries,
            'form' => $form->createView(),
        ]);
    }
}

templates/Dashboard/edit_serial_letter.html.twig
{#
 Copyright (C) 2022 by Luc Hamers <vereniging@hamers.de>

 This file is part of Vereniging.

 Vereniging is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Vereniging is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Vereniging.  If not, see <https://www.gnu.org/licenses/>.
#}

{% extends 'layout.html.twig' %}
{% block title %} Edit serial letter {% endblock %}
{% set dashboard_subpage = {'Select serial letter' : 'select_serial_letter', 'Edit serial letter' : ''} %}

{% block body %} 

{{ parent() }}
<div class="container-fluid">
    <div class="card mt-3 mb-2">
        <div class="card-body">
            {{ form_start(form, {'attr': {'id': 'serial_letter_form'}}) }}
            {{ form_errors(form) }}
            <div class="row">
                <div class="col-md-2">
                </div>
            {% for content in form.serialLetterContents %}
                <div class="col-md-5 text-center">
                    <h6>{{ content.vars.data.language.language }}</h6>
                </div>
            {% endfor %}
            </div> <!-- row -->
            <div class="row">
                <div class="col-md-2 text-right">
                    {{ form_label(form.serialLetterContents[0].letterTitle) }}
                </div>
                {% for content in form.serialLetterContents %}
                    <div class="col-md-5 text-center">
                        {{ form_errors(content.letterTitle) }}
                        {{ form_widget(content.letterTitle, { 'attr': {'class': 'autosave'} }) }}
                    </div>
                {% endfor %}
            </div> <!-- row -->
            <br />
            <div class="row">
                <div class="col-md-2 text-right">
                    {{ form_label(form.serialLetterContents[0].content) }}
                </div>
                {% for content in form.serialLetterContents %}
                    <div class="col-md-5 text-center">
                        {{ form_errors(content.content) }}
                        {{ form_widget(content.content, { 'attr': {'class': 'autosave ' ~ content.vars.data.language.locale } }) }}
                    </div>
                {% endfor %}
            </div> <!-- row -->
            <br />
            <div class="row">
                <div class="col-md-2 text-right">
                    {{ form_label(form.firstSignatureMember) }}
                </div>
                <div class="col-md-3 text-center">
                    {{ form_errors(form.firstSignatureMember) }}
                    {{ form_widget(form.firstSignatureMember, { 'attr': {'class': 'autosave'} }) }}
                </div>
                <div class="col-md-3 text-center">
                    {{ form_errors(form.secondSignatureMember) }}
                    {{ form_widget(form.secondSignatureMember, { 'attr': {'class': 'autosave'} }) }}
                </div>
            </div> <!-- row -->
            <div class="row">
                <div class="col-md-2 text-right">
                    {{ form_label(form.firstSignatureMembersFunction) }}
                </div>
                <div class="col-md-3 text-center">
                    {{ form_errors(form.firstSignatureMembersFunction) }}
                    {{ form_widget(form.firstSignatureMembersFunction, { 'attr': {'class': 'autosave'} }) }}
                </div>
                <div class="col-md-3 text-center">
                    {{ form_errors(form.secondSignatureMembersFunction) }}
                    {{ form_widget(form.secondSignatureMembersFunction, { 'attr': {'class': 'autosave'} }) }}
                </div>
            </div> <!-- row -->
            <div class="row">
                <div class="col-md-2 text-right">
                </div>
                <div class="col-md-6 text-center">
                    {{ form_errors(form.signatureUseTitle) }}
                    {{ form_widget(form.signatureUseTitle, { 'attr': {'class': 'autosave'} }) }}
                </div>
            </div> <!-- row -->
            <br />
            <div class="row">
                <div class="col-md-2 text-right">
                </div>
                <div class="col-md-10">
                    {% for content in form.serialLetterContents -%}
                        {%- set language = content.vars.data.language.language -%}
                        <button type="submit" class="btn btn-outline-secondary" name="preview{{ language }}">{% trans %}Generate PDF preview{% endtrans %} - {{ language }}</button>
                    {% endfor -%}
                    <div id="status" class="far fa-save fa-2x" style="color:gray;vertical-align: middle"></div>
                </div>
            </div> <!-- row -->

            {{ form_end(form) }}
        </div> <!-- panel-body -->
    </div> <!-- panel -->
</div>  <!-- container -->

<script>
    /*
     * Hide and clear the second signature member when the first member selection is empty
     */
    function showHideSecondMember() {
        if ($('#serial_letter_firstSignatureMember').val()) {
            $('#serial_letter_secondSignatureMember').show();
            $('#serial_letter_secondSignatureMembersFunction').show();
        } else {
            // Hide second members function and empty the options, so the options are gone when it is shown again.
            $('#serial_letter_secondSignatureMembersFunction').hide();
            $('#serial_letter_secondSignatureMembersFunction').empty();
            // Hide and clear the second members selection.
            $('#serial_letter_secondSignatureMember').hide();
            $('#serial_letter_secondSignatureMember').val('');
        }
    }

    // Initialize the visibility of the second member on startup
    $(document).ready(function(){
        showHideSecondMember();
    });

    $('#serial_letter_firstSignatureMember').change(function() {
        showHideSecondMember();
    });

    $firstMember = $('#serial_letter_firstSignatureMember');
    $firstMember.change(function() {
        var $form = $(this).closest('form');
        var $data = $form.serialize();
        // Submit data via AJAX to the form's action path.
        $.ajax({
            url : $form.attr('action'),
            type: $form.attr('method'),
            data : $data,
            success: function(html) {
                // Replace current position field ...
                $('#serial_letter_firstSignatureMembersFunction').replaceWith(
                    // ... with the returned one from the AJAX response.
                    $(html).find('#serial_letter_firstSignatureMembersFunction')
                );
                // Position field now displays the appropriate positions.
            }
        });
    });

    $secondMember = $('#serial_letter_secondSignatureMember');
    $secondMember.change(function() {
        var $form = $(this).closest('form');
        var $data = $form.serialize();
        // Submit data via AJAX to the form's action path.
        $.ajax({
            url : $form.attr('action'),
            type: $form.attr('method'),
            data : $data,
            success: function(html) {
                // Replace current function field ...
                $('#serial_letter_secondSignatureMembersFunction').replaceWith(
                    // ... with the returned one from the AJAX response.
                    $(html).find('#serial_letter_secondSignatureMembersFunction')
                );
                // Function field now displays the appropriate functions for the selected member.
            }
        });
    });

    var timeoutId;
    // This method implements the autosave function of the page. Each time one of the form elements changes, the timer
    // is started again. When there is no activity for 3s, than all content is saved via an ajax call.
    function ProlongTimer() {
        // Show the save icon in yellow (there has been a value change)
        $('#status').attr('class', 'far fa-save fa-2x').attr('style', 'color:Orange;');
        if (timeoutId) clearTimeout(timeoutId);
        // When the timeout of 750ms is reached, than do ajax call to save
        timeoutId = setTimeout(function (e) {
            // Show it is saved icon, which is faced out to a gray floppy symbol afterwards.
            $('#status').attr('class', 'fas fa-check fa-2x').attr('style', 'color:MediumSeaGreen;').fadeOut(1000, function(){
                $('#status').attr('class', 'far fa-save fa-2x').attr('style', 'color:gray;')
            });

            // Save forms content to the serial letter controller
            var $form = $('#serial_letter_form');
            var $data = $form.serialize();
            // Submit data via AJAX to the form's action path.
            $.ajax({
                url : $form.attr('action'),
                type: $form.attr('method'),
                data : $data,
            });
        }, 3000);
    }

    // This is used for the select fields
    $('.autosave').change(function (){
        ProlongTimer();
    });

</script>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/tinymce/tinymce.min.js') }}"></script>
    <script>
        {% for content in form.serialLetterContents %}
        tinymce.init({
            selector: 'textarea.{{ content.vars.data.language.locale }}',
            init_instance_callback: function (editor) {
                // Whenever there is a keyup event, check if the content changed and if so, trigger ProLongTimer, for
                // the autosave function.
                editor._lastChange = editor.getContent();
                editor.on('keyup ExecCommand', function (e) {
                    // This is needed,because the value of the textarea is not updated automatically, which would send
                    // the old value in the ajax call.
                    tinymce.triggerSave();
                    var value = editor.getContent();
                    if (value !== editor._lastChange) {
                        ProlongTimer();
                        editor._lastChange = value;
                    }
                });
            },
            height : 350,
            // toolbar: 'undo redo cut copy paste styleselect bold italic alignleft aligncenter alignright bullist numlist outdent indent code',
            toolbar: " insertfile undo redo | bold italic subscript superscript | alignleft aligncenter alignright | bullist numlist | table | code pagebreak | jbimages image link | template-button variable-button",
            plugins: [
                "advlist autolink lists link image charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste pagebreak noneditable"
            ],
            advlist_bullet_styles: "",
            advlist_number_styles: "",
            table_appearance_options: false,
            table_advtab: false,
            table_cell_advtab: false,
            table_row_advtab: false,
            table_responsive_width: false,
            menubar: false,
            paste_as_text: true,
            pagebreak_separator: "<!--newpage-->",
            setup: function (editor) {
                editor.addButton('template-button', {
                    type: 'listbox',
                    text: '{% trans %}Templates{% endtrans %}',
                    icon: false,
                    onselect: function (e) {
                        editor.insertContent(this.value());
                    },
                    values: [
                        {% for template in templates[content.vars.data.language.locale] %}
                        { text: '{{ template.templateName }}', value: '{{ template.templateContent|replace({"\n":' ', "\r":' '})|raw }}' },
                        {% endfor %}
                    ]
                });
                editor.addButton('variable-button', {
                    type: 'listbox',
                    text: '{% trans %}Variables{% endtrans %}',
                    icon: false,
                    onselect: function (e) {
                        editor.insertContent(this.value());
                    },
                    values: [
                        {# add all variables to the menu. The element is shown as a text block surrounded with a gray dotted line, the content cannot be edited -#}
                        {% for variable in variables -%}
                        {% if variable == '-' -%}
                        {text: '-'},
                        {% else -%}
                        { text: '{{ variable|trans }}', value: '<span style="border: thin dotted grey;" class="mceNonEditable" data-variable="{{ variable }}">{{ variable | trans }}</span>'},
                        {% endif -%}
                        {% endfor -%}
                    ]
                });
            }
        });
        {% endfor %}

    </script>
 {% endblock %}